# Generated by Django 4.2.6 on 2023-10-21 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lecture_name", models.CharField(max_length=200)),
                ("lecture_number", models.CharField(max_length=11)),
                ("department", models.CharField(max_length=10)),
                ("semester", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("bulletpoints", models.TextField()),
                ("summary", models.TextField()),
                ("tags", models.ManyToManyField(related_name="topics", to="TLDR.tag")),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("presentation_date", models.DateField()),
                ("infered_titel", models.CharField(max_length=100)),
                ("presenters", models.TextField()),
                (
                    "video_file_path",
                    models.FilePathField(verbose_name="/home/admin/videos"),
                ),
                ("video_source_url", models.URLField()),
                (
                    "lecture_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="TLDR.lecture"
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        related_name="discussed_in", to="TLDR.topic"
                    ),
                ),
            ],
        ),
    ]
