# Generated by Django 4.2.6 on 2023-10-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLDR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file_path',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_source_url',
        ),
        migrations.AddField(
            model_name='topic',
            name='chunk1',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='chunk2',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='chunk3',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='source_url',
            field=models.URLField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='transcript',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
