# Generated by Django 4.2.6 on 2023-10-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TLDR", "0002_remove_video_video_file_path_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.AddField(
            model_name="topic",
            name="tags",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
